name: staging

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      pr: ${{ steps.meta.outputs.version }}
      image: ${{ steps.meta.outputs.tags }}
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/metadata-action@v3
      id: meta
      with:
        images: ghcr.io/vives-projectwerk-2021/pulu-frontend
        tags: type=ref,event=pr
    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          VUE_APP_WS=${{ secrets.VUE_APP_WS }}
          VUE_APP_BACKEND_BASE_URL=${{ secrets.VUE_APP_BACKEND_BASE_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: composite action
        uses: vives-projectwerk-2021/pulu-action@main
        with: 
          pulu_build: pulu-frontend.${{ needs.build.outputs.pr }}
          ssh_deploy_key: ${{secrets.SSH_DEPLOY_KEY}}
          github_token: ${{ secrets.GITHUB_TOKEN }}
