name: "composite for pulu"
description: "action to be called for use in other actions"

inputs:
  pulu_build:
    description: "which pulu endpoint + build output"
  ssh_deploy_key: 
    description: "ssh key for the deployment"
  github_token:
    description: "github token"
  image:
    description: "image"

runs:
  using: "composite"
  steps:
    - uses: shimataro/ssh-key-action@v2
      with:
        key:  ${{ inputs.ssh_deploy_key }}
        known_hosts: 'no-hosts'
    - name: install pulu-cli
      shell: bash
      run: |
        curl -L https://github.com/vives-projectwerk-2021/pulu-cli/releases/latest/download/pulu-linux -o /usr/local/bin/pulu
        chmod +x /usr/local/bin/pulu
    - id: sandbox
      shell: bash
      run: |
        pulu exec staging "docker rm -f ${{ inputs.pulu_build }}"
        export PULU_FRONTEND_PORT=$(ruby -e 'require "socket"; puts Addrinfo.tcp("", 0).bind {|s| s.local_address.ip_port }')
        pulu exec staging " \
        docker run -t --name ${{ inputs.pulu_build }} --privileged \
        -v /devops/.ssh/id_rsa:/root/.ssh/id_rsa \
        -v /devops/deployment/staging/.env:/pulu.env \
        -p $PULU_FRONTEND_PORT:8080 \
        -e PULU_FRONTEND="${{ inputs.image }}" \
        ghcr.io/vives-projectwerk-2021/pulu-sandbox \
        make production"
        pulu exec staging "docker start ${{ pulu_build }}"
        echo "::set-output name=PORT::$PULU_FRONTEND_PORT"
    - uses: thollander/actions-comment-pull-request@v1
      with:
        message: 'You can now proxy this deployment: `pulu proxy staging ${{ steps.sandbox.outputs.PORT }}`'
        GITHUB_TOKEN: ${{ inputs.github_token }}
