name: "composite for pulu"
description: "action to be called for use in other actions"

inputs:
  pulu_build:
    description: "build output"
  ssh_deploy_key: 
    description: "ssh key for the deployment"
  github_token:
    description: "github token"
  image:
    description: "image"
  pulu_endpoint:
    description: "which endpoint this action is being used for"

runs:
  using: "composite"
  steps:
    - uses: shimataro/ssh-key-action@v2
      with:
        key:  ${{ inputs.ssh_deploy_key }}
        known_hosts: 'no-hosts'
    - name: install pulu-cli
      shell: bash
      run: |
        curl -L https://github.com/vives-projectwerk-2021/pulu-cli/releases/latest/download/pulu-linux -o /usr/local/bin/pulu
        chmod +x /usr/local/bin/pulu
    - id: sandbox
      shell: bash
      run: |
        pulu exec staging "docker rm -f ${{ inputs.pulu_build }}"
        pulu exec staging "docker volume prune -f"
